version: 3

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - network
  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - mongo
      
networks:
  network:
    driver: bridge

volume:
  data:
    driver: local